[bot]
check_interval = 2    # 机器人巡检时间间隔（单位：秒）
friend_colddown_time = 30     #好友农场无可操作事件后，机器人休眠时间（单位：秒）
debug_mode = False      # 调试模式，开启后每一轮巡检完成后都需要按【ctrl+s】键才会进行下一轮巡检
enable_process_self = True      # 是否启用机器人对自己农场的处理(禁用后下面的详细功能配置将无效)
enable_process_friend = True    # 是否启用机器人对好友农场的处理

[self]  # 针对自己农场的详细功能配置项
enable_harvest = True      # 是否启用收获功能
enable_remove_bug = True      # 是否启用除虫功能
enable_remove_grass = True      # 是否启用除草功能
enable_watering = True      # 是否启用浇水功能
# enable_plant = True      # 是否启用种菜功能(功能还在开发中)

