[bot]
check_interval = 2    # 机器人巡检时间间隔（单位：秒）
friend_colddown_time = 30     #好友农场无可操作事件后，机器人休眠时间（单位：秒）
debug_mode = False      # 调试模式，开启后每一轮巡检完成后都需要按【ctrl+s】键才会进行下一轮巡检
enable_process_self = True      # 是否启用机器人对自己农场的处理(禁用后下面的详细功能配置将无效)
enable_process_friend = True    # 是否启用机器人对好友农场的处理

[self]  # 针对自己农场的详细功能配置项
enable_harvest = True      # 是否启用收获功能
enable_remove_bug = True      # 是否启用除虫功能
enable_remove_grass = True      # 是否启用除草功能
enable_watering = True      # 是否启用浇水功能
# enable_plant = True      # 是否启用种菜功能(功能还在开发中)

[threshold]     # 视觉匹配阈值配置项
help_remove_bugs_frame = 0.6    # 好友列表有虫图标阈值
help_remove_grass_frame = 0.6    # 好友列表有草图标阈值
help_watering_frame = 0.6    # 好友列表有干土地图标阈值
can_steal_frame = 0.6       # 好友列表有可偷取图标阈值
close_x_frame = 0.6         # 关闭按钮 X 图标阈值
go_home_frame = 0.5         # 回家按钮图标阈值
steal_all_frame = 0.5       # 一键偷取图标阈值
watering_all_frame = 0.4    # 一键浇水图标阈值
remove_all_grass_frame = 0.4    # 一键除草图标阈值
remove_all_bugs_frame = 0.5     # 一键除虫图标阈值
harvest_all_frame = 0.4     # 一键收获图标阈值
harvest_one_frame = 0.4     # 单个可收获图标阈值
friend_icon_frame = 0.47    # 好友图标阈值
welcome_back_frame = 0.65   # 欢迎回来界面阈值
get_new_seed_frame = 0.4    # 获得新种子界面阈值（活动）
level_up_frame = 0.6        # 升级界面阈值
reconnect_frame = 0.5       # 重连按钮阈值